var MSG_ONLY="Only "
var MSG_ARE_ALLOWED=" are allowed !"
var MSG_ALPHABETS=" Alphabets"
var MSG_NUMBERS=" Numbers"
var MSG_SPACES=" Spaces"
var MSG_CUSTOM_PATTERN="values matching pattern "
var NO_CHAR_ALLOWED="No Characters are allowed !"
var ENTER_VALUE_BETWEEN="Please enter the value between "
var FLOAT_RANGE='-2147483648 and 2147483647'
var INTEGER_RANGE='-32768 and 32767'
var ENTER_CORRECT_VALUE="Please enter the correct value."
var ENTER_CORRECT_VALUE_FOR="Enter Correct value for ";
var PRECISION_VALUE="Precision should be in Range of 0 to ";
var CORRECT_VALUE="Value is not in Range";
var FLOAT_LENGTH="Maximum length can be 15";
var INVALID_EMAIL="Please enter valid Email Id."
var BATCH_MSG="Do you want to Save Current Data ?";
var INVALID_PHONE="Please enter valid phone number."
var MINMAXVALUEMSG="Value should be between ";
var MSG_AND=" and ";
var ONPASTE_MSG=" characters can be pasted in this field since it has a character limit of ";
var ONLY_FIRST="Only the first ";
var YES="Yes";
var NO="No";
var SPACE_NOT_ALLOWED="Spaces not allowed while pasting";
var NUMBER_NOT_ALLOWED="Numbers not allowed while pasting";
var ALPHABET_NOT_ALLOWED="Alphabets not allowed while pasting";
var NOT_ALLOWED=" not allowed while pasting";
var INVALID_SESSION="Invalid Session";
var SELECT="Select";
var AUTH_UNSUCCESSFUL="Invalid login information.";
var AUTH_UNSUCCESSFUL_TITLE="Login Failed";
var BLANK_PASSWORD="Please enter your password."
var IS_NOT_ALLOWED=" is not allowed";
var INVALID_POSITION="Invalid position for ";
var CANNOT_USE="Cannot use ";
var MIN_VALUE_ERROR="Min value of the control is ";
var MAX_VALUE_ERROR="Max value of the control is ";
var SELECT_ALL="Select all";
var NONE_SELECTED="None selected";
var SELECTED_TEXT="selected";
var AUTH_INVALIDUSER="Please enter Email ID";
var AUTH_INVALIDUSER_TITLE="Login Failed";
var OPT_SEND_MSG="OTP has been sent to";
var OTP_EXPIRED="OTP has expired.";
var OTP_EXPIRED_MSG="To get another OTP at <> please press the resent button";
var DIDNT_GET_OTP="Didn't get the OTP?";
var SERVER_ERROR="Some error occurred at server end. Please check server logs.";
var SERVER_ERROR_TITLE="Server Error";
var LEFT="left";
var RIGHT="right";
var CAMERA_FILE_UPLOAD="File Uploaded Successfully";
var FRONT_CAMERA_ERROR="Front Camera mode is not supported.Please rotate the camera view";
var BACK_CAMERA_ERROR="Back Camera mode is not supported.Please rotate the camera view";
var CAMERA_IMAGE_ERROR="Camera is not supported with your device";
var ACCESS_DENIED_LOCATION="User denied the request for Geolocation.";
var LOCATION_UNAVILABLE="Location information is unavailable.";
var TIME_OUT_LOCATION="The request to get user location timed out.";
var ERROR_OCCURRED="An unknown error occurred.";
var NAV_TITLE="Navigation Error";
var MANDATORY_TITLE="Mandatory Alert";
var DATA_TITLE="Invalid Data";
var SAVE_TITLE="Save Failed";
var ERROR_TITLE="Error";
var SUCCESS_TITLE="Success";
var WORKITEM="Workitem";
var CREATEMSG="created successfully";
var CREATE_TITLE="Workitem Created";
var MIN_WIDTH_ERROR="Min Width should be less than Max Width.";
var MAX_WIDTH_ERROR="Max Width should be greater than Min Width.";
var MAX_FILE_SIZE_ERROR="The maximum file size can be only of 10MB";
var SLIDER_MAX="max";
var SLIDER_MIN="min";
var SLIDER_VALUE="value";
var MAX_MIN_ERROR="max must be greater than min";
var MIN_MAX_ERROR="min must be less than max";
var VALUE_MIN_ERROR="value must be greater than or equal to min";
var VALUE_MAX_ERROR="value must be less than or equal to max";
var TILEALIGNLABEL="TileAlignLabel";
var SLIDER_UNIT="unit";
var DOC_ERROR="Error in uploading attachment please try again.";
var orientation_msg="This Form is not optimised for Landscape mode.Please rotate your device to Portrait mode for better experience";
var DEL_ERROR="Predefined properties cannot be deleted";
var WIDTH_PX_LISTVIEW="Now Columns width will be calculated according to px ";
var NO_DATA_FOUND="No Data Found";
var SUBMIT_APPLICATION="Do you want to submit the Application?";
var CLOSE_WINDOW="Please close the window.";
var EXIST_APPLICATION="You have one already registered Application.";
var SELECT_EXIST_APPLICATION="Do you want to load the existing Application or create a new one? ";
var LOGOUT_MSG="Do you want to logout?";
var APP_SUB_SUCS="Your Application has been submitted.";
var DELETE_DOC_MSG="Are you sure you want to remove ";
var CANCEL="Cancel";
var YES_REMOVE="Yes, Remove";
var TILE_SELECTION="No of Tiles to be selected";
var SINGLE="Single";
var MULTIPLE="Multiple";
var DEFAULT_TILE_SELECTION="Default Tile to be selected";
var NONE="none";
var TILE_MAD_MSG="Make Tile Selection Mandatory";
var ERROR_TXT="Error Text";
var TILE_PLACEHOLDER="This Message will be displayed when tiles are not selected";
var FORM_SAVE_MSG="Your Form has been Saved.";
var OPEN_APPLICATION="Open existing Application";
var CREATE_NEW="Create New";
var INFO="Info";
var DAY1="Su";
var DAY2="Mo";
var DAY3="Tu";
var DAY4="We";
var DAY5="Th";
var DAY6="Fr";
var DAY7="Sa";
var MONTH1="Jan";
var MONTH2="Feb";
var MONTH3="Mar";
var MONTH4="Apr";
var MONTH5="May";
var MONTH6="Jun";
var MONTH7="Jul";
var MONTH8="Aug";
var MONTH9="Sep";
var MONTH10="Oct";
var MONTH11="Nov";
var MONTH12="Dec";
var FULLMONTH1="January";
var FULLMONTH2="February";
var FULLMONTH3="March";
var FULLMONTH4="April";
var FULLMONTH5="May";
var FULLMONTH6="June";
var FULLMONTH7="July";
var FULLMONTH8="August";
var FULLMONTH9="September";
var FULLMONTH10="October";
var FULLMONTH11="November";
var FULLMONTH12="December";
var ERROR_MSG_INTERFACE="No supported webcam interface found";
var DOC_COMMENT="write comments";
var TILE_MAX="Cant enter more than max ";
var TILE_MIN="Cant enter less than min ";
var THE_VALUE="The value";
var INCOMPATIBLE_MSG="is not compatible with";
var FIELD="field";
var TABLE="table";
var ROW="row";
var COLUMN="column";
var OF="of";
var DELETE_Table_MSG="Do you want to delete the row ?";
var DOCUMENT_NAME_MISSING="Enter Docuement Name first";
var DUPLICATE_DOCUMENT_NAME="Docuement Name already set";
var Doc_Comments_label="Comment";
var Doc_Comments_Msg="Please enter the comment";
var SAVEEXITMSG="Do you want to save and exit ?";
var DELETE="Delete";
var SHOW_LOGOUT_MSG="You have been logged out successfully.";
var SPACE_NOT_ALLOWED_FOR="Spaces not allowed for ";
var NUMBER_NOT_ALLOWED_FOR="Numbers not allowed for ";
var ALPHABET_NOT_ALLOWED_FOR="Alphabets not allowed for ";
var SEARCH="Search";
var PDF_FILE_DOWNLOAD_SUCCESS="File Downloaded Successfully."
var PDF_FILE_DOWNLOAD_FAILURE="File Download Failed."